title: Xueming Li # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist, PhD in Microelectronics 
  <br><br>
  
  <a href="https://www.linkedin.com/in/lixuemingpku/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-102423960-1 # your Google Analytics tracking ID here
